---
server:
  error:
    include-stacktrace: never
  port: 5555

logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.neo4j.*: INFO
    com.memorynotfound: DEBUG
    org.apache.kafka.*: ERROR

spring:
  main:
    banner-mode: off
  application:
    name: api-gateway
  cloud:
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
    gateway:
      default-filters:
        #- DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service
            #uri: https://s10-14-ft-api-users.azurewebsites.net
          uri: lb://user-service
          predicates:
            - name: Path
              args:
                pattern: "/api/v1/**"
          filters:
            - CustomAuthenticationFilter
        - id: security-current-session
         # uri: https://s10-14-ft-api-security.azurewebsites.net
          uri: http://localhost:8081
          predicates:
            - Path=/api/accounts/current-session
          filters:
            - CustomAuthenticationFilter
        - id: loans-application
          uri: lb://loans-application
          predicates:
            - name: Path
              args:
                pattern: "/api/**"
          filters:
            - CustomAuthenticationFilter
        - id: security
        #  uri: https://s10-14-ft-api-security.azurewebsites.net
          uri: http://localhost:8081
          predicates:
            - name: Path
              args:
                pattern: "/api/**"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: https://s10-14-ft-eurekaserver.azurewebsites.net/eureka/
      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0

jwt:
  secret: RandomSecretKey123456789!RandomSecretKey123456789!RandomSecretKey123456789!
...